Wrong (re)declaration of isCallable
OpenConext/SamlValueObject pull request #12
Opened 2016-10-07 08:53 UTC by mrvanes

I know there is a pull request to remove isCallable declaration in Assert by upgrading Beberlei/assert, but as long as that is not accepted, this declaration of isCallable breaks EB:

Declaration of OpenConext\Value\Assert\Assertion::isCallable($value, $message, $propertyPath) should be compatible with Assert\Assertion::isCallable($value, $message = NULL, $propertyPath = NULL) [/opt/OpenConext/OpenConext-engineblock-5.0.0/vendor/openconext/saml-value-object/src/OpenConext/Value/Assert/Assertion.php:0]

2017-06-11 09:50 UTC, tvdijen commented
I just ran into the same thing.. Apparently it has never been merged, so *bump*

2017-06-13 07:17 UTC, MKodde commented
The proposed change is valid and I don't see any problem in changing the order of the parameters. This change does involve a little more maintenance tho. The calls to the `isCallable` method should be updated to correctly use the new method signature.

For example see the `tests/OpenConext/Value/Assert/AssertionTest.php` tests.

I did not find usages of the `isCallable` method outside this library. I've searched in the Stepup and openconnext development environments. I'm not aware if this library is used in other projects.

2017-06-15 05:29 UTC, thijskh requested changes
As per MKodde

2018-01-20 10:33 UTC, tvdijen commented
Can we just go with #11 and merge that, since that one has already been approved and is just waiting for a merge?

2018-01-20 11:21 UTC, thijskh commented
Let's do that when there's a need to work on SVB.

2018-01-20 11:24 UTC, tvdijen commented
There is....  it has a bug that's flooding my logs!

2018-01-20 11:28 UTC, thijskh commented
@MKodde @jorissteyn Can you review?

2018-01-20 12:43 UTC, tvdijen commented
Thanks!  #11 runs fine, even with the latest 2.8.1 version of beberlei/assert

2018-01-22 09:37 UTC, MKodde commented
#11 was released as version 1.3.1. 
Closing this PR.

2018-01-22 09:38 UTC, closed without merging